version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 224678269500.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t blacklist_ms .
      - docker tag blacklist_ms:latest 224678269500.dkr.ecr.us-east-1.amazonaws.com/blacklist_ms:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 224678269500.dkr.ecr.us-east-1.amazonaws.com/blacklist_ms:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"Container-blacklist-ms","imageUri":"224678269500.dkr.ecr.us-east-1.amazonaws.com/blacklist_ms:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"224678269500.dkr.ecr.us-east-1.amazonaws.com/blacklist_ms:latest"}' > imageDetail.json
      - cat imagedefinitions.json
artifacts:
  files:
    - "**/*"
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
