version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 876360250786.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image... 
      - docker build -t entrega-3:latest .
      - docker tag entrega-3:latest 876360250786.dkr.ecr.us-east-1.amazonaws.com/entrega-3:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 876360250786.dkr.ecr.us-east-1.amazonaws.com/entrega-3:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"Container-devops-entrega-3","imageUri":"876360250786.dkr.ecr.us-east-1.amazonaws.com/entrega-3:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"876360250786.dkr.ecr.us-east-1.amazonaws.com/entrega-3:latest"}' > imageDetail.json
      - cat imagedefinitions.json 
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
