version: '3.5'

services:

  api:
    image: api_srvc
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    #command: gunicorn -w 4 -b 0.0.0.0:5000 application:application
     